# -*- coding: utf-8 -*-
"""Combine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kuGWSz4dZGN7IzbAG2EkNjmdxFp6DnHu
"""

import pandas as pd 
import numpy as np 

if __name__ == "__main__":
  base = 'data/trasnformer/'
  base_pred = 'pred_data'
  base_score = 'score_data'
  indexes = list(range(0, 50))
  pred_data_final = pd.DataFrame()
  score_data_final = pd.DataFrame()
  for i in indexes:
    df1 = pd.read_csv(base + base_pred + str(i) + '.csv')
    df2 = pd.read_csv(base + base_score + str(i) + '.csv')
    pred_data_final = pd.concat([pred_data_final, df1])
    score_data_final = pd.concat([score_data_final, df2])
  

  pred_data_final.to_csv('pred_data_final')
  score_data_final.to_csv('score_data_final')